services:
  - type: web
    name: retrospring
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
- key: SECRET_KEY_BASE
  value: 4d17914b6ad4a8d4fc712a6b51a4f5eac97ff24c0c6941bb7ed4ab4f3c2aa408b09b96a62811bdb1b40387dd8e7b9f7f0a848346e6be1514e9f42d1218e1b839
      - key: DATABASE_URL
        fromDatabase:
          name: retrospring-db
          property: connectionString
